version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080